steps:

  - id: go-prepare-01
    name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'init', 'source.cloud.google.com/hybrid-cloud-22365/github_stefanhansatos_migros-showcase']
    env:
      - 'GO111MODULE=on'
      - 'GOPATH=/go'

  - id: go-prepare-02
    name: 'gcr.io/cloud-builders/go'
    args: ['mod', 'vendor']
    env:
      - 'GO111MODULE=on'
      - 'GOPATH=/go'
      - 'GOPROXY=https://proxy.golang.org'

  - id: deploy-prepare-01
    name: 'gcr.io/hybrid-cloud-22365/migros-showcase-bash'
    args: ['pipeline/00_prepare-deployment.bash']

  - id: gsutil_cp_zip_file
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/functions/version-0-0-1-development.zip',
           'gs://hybrid-cloud-22365_migros-showcase-devops/version-0-0-1-development.zip'
    ]
